x-kafka-common-env: &kafka-common-env
  CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  KAFKA_PROCESS_ROLES: 'broker,controller'
  KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT'
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
  KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_MIN_INSYNC_REPLICAS: 2
  KAFKA_TRANSACTION_MAX_TIMEOUT_MS: 120000

services:
  kafka1:
    image: confluentinc/cp-kafka:7.9.2
    container_name: kafka1
    ports:
      - "29092:29092"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: 'PLAINTEXT://kafka1:9092,PLAINTEXT_EXTERNAL://localhost:29092,CONTROLLER://kafka1:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092,PLAINTEXT_EXTERNAL://localhost:29092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    volumes:
      - kafka1_data:/var/lib/kafka/data
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD-SHELL", "cub kafka-ready -b kafka1:9092 3 30"]
      interval: 15s
      timeout: 10s
      retries: 10


  kafka2:
    image: confluentinc/cp-kafka:7.9.2
    container_name: kafka2
    ports:
      - "29093:29093"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: 'PLAINTEXT://kafka2:9092,PLAINTEXT_EXTERNAL://localhost:29093,CONTROLLER://kafka2:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:9092,PLAINTEXT_EXTERNAL://localhost:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    volumes:
      - kafka2_data:/var/lib/kafka/data
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD-SHELL", "cub kafka-ready -b kafka2:9092 3 30"]
      interval: 15s
      timeout: 10s
      retries: 10

  kafka3:
    image: confluentinc/cp-kafka:7.9.2
    container_name: kafka3
    ports:
      - "29094:29094"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: 'PLAINTEXT://kafka3:9092,PLAINTEXT_EXTERNAL://localhost:29094,CONTROLLER://kafka3:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:9092,PLAINTEXT_EXTERNAL://localhost:29094'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    volumes:
      - kafka3_data:/var/lib/kafka/data
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD-SHELL", "cub kafka-ready -b kafka3:9092 3 30"]
      interval: 15s
      timeout: 10s
      retries: 10

  kafdrop:
    image: obsidiandynamics/kafdrop:4.1.0
    container_name: kafdrop
    ports:
      - "19000:9000"
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    environment:
      KAFKA_BROKERCONNECT: "kafka1:9092,kafka2:9092,kafka3:9092"
      SERVER_SERVLET_CONTEXTPATH: "/"
    networks:
      - kafka-network

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:

networks:
  kafka-network:
    driver: bridge
