spring:
  application:
    name: spring-kafka-labs
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.cloudevents.kafka.CloudEventSerializer
      properties:
        io.cloudevents.kafka.encoding: structured
        io.cloudevents.kafka.event_format: application/cloudevents+json
    consumer:
      group-id: payment-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.cloudevents.kafka.CloudEventDeserializer
      auto-offset-reset: earliest

payment:
  kafka:
    topics:
      request: payment-requests
      response: payment-responses